# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:

  email_provider_username: "i.am.jongmin.kim@gmail.com"
  email_provider_password: "rlawhdals"
  mailchimp_api_key: "6e157eb7ca1d0c17cc6fe362270f9456-us10" 
  mailchimp_list_id: "17a7cca1b7"
  domain_name: example.com 
  owner_email: "i.am.jongmin.kim@gmail.com"
  secret_key_base: 72ffb3910f04c0f045edb43e8d204b8f43dd1730d13d08f03faf3027efbdbf9c9149352286561e367689ce03f753f1c3d34861d2d3edf9fd2bf0934d3078c660

test:
  secret_key_base: fb0905cf4d3ce57ff62fa13cb7aff128f51bab3a04fed6dcfdc4447eebc45dc6a40cb7969e287a7ed5f9c03d94ecb7546d928ba8bd1c7824fa736e2fe69f2759

# Do not keep production secrets in the repository,
# instead read values from the environment.

production: 
  email_provider_username: "i.am.jongmin.kim@gmail.com"
  email_provider_password: "rlawhdals"
  mailchimp_api_key: "6e157eb7ca1d0c17cc6fe362270f9456-us10" 
  mailchimp_list_id: "17a7cca1b7"
  domain_name: <%= ENV["example.com "] %> 
  owner_email: "i.am.jongmin.kim@gmail.com"
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
 